name: Run tests

on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  handle-syncwith:
    if: github.event_name == 'pull_request'
    name: Call Reusable SyncWith Handler
    uses: NilFoundation/ci-cd/.github/workflows/reusable-handle-syncwith.yml@v1
    with:
      ci-cd-ref: 'v1'
    secrets: inherit

  run_tests:
    needs: [ handle-syncwith ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: cachix/install-nix-action@v23
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Nix
        run: |
          mkdir -p ~/.config/nix
          echo "extra-experimental-features = nix-command flakes" > ~/.config/nix/nix.conf

      - name: Build
        run: nix build -L .?submodules=1#

      - name: Run tests
        run:
          nix flake check -L .?submodules=1#
