name: Run tests

on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SUITE_REPO: "NilFoundation/crypto3"
  LIB_NAME: "blueprint"
  CACHE_NAME: checkout-job-cache

jobs:
  checkout:
    runs-on: [self-hosted, tests-runner]
    strategy:
      matrix:
        compiler: [gcc, clang]
    name: Checkout and build using ${{ matrix.compiler }}
    steps:
      - name: Cleanup # TODO - move to scripts on runner
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Checkout suite
        uses: actions/checkout@v3
        with:
          repository: ${{ env.SUITE_REPO }}
          submodules: recursive

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          path: ./libs/${{ env.LIB_NAME }}
          submodules: recursive

      - name: Set additional env
        run : |
          echo "BUILD_NAME=${{ env.CACHE_NAME }}-${{ matrix.compiler }}" >> $GITHUB_ENV
          echo "BUILD_ARCHIVE_NAME=${{ env.CACHE_NAME }}-${{ matrix.compiler }}.tar.gz" >> $GITHUB_ENV

          if [ ${{ matrix.compiler }} == clang ]; then
            echo "COMPILERS=-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++" >> $GITHUB_ENV
          fi
          if [ ${{ matrix.compiler }} == gcc ]; then
            echo "COMPILERS=-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++" >> $GITHUB_ENV
          fi

      - name: Cmake and build
        env:
          CMAKE_ARGS: "
            -DCMAKE_BUILD_TYPE=Debug
            -DBUILD_SHARED_LIBS=FALSE
            -DBUILD_TESTS=TRUE
            "
        run: |
          mkdir build
          cd build
          cmake ${{ env.CMAKE_ARGS }} ${{ env.COMPILERS }} ..

      - name: Archive build results
        run: |
          touch ${{ env.BUILD_ARCHIVE_NAME }}
          tar -czf ${{ env.BUILD_ARCHIVE_NAME }} --exclude=${{ env.BUILD_ARCHIVE_NAME }} .

      - name: Cache archived job output
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_NAME }}
          path: ${{ env.BUILD_ARCHIVE_NAME }}
          retention-days: 1


  run_tests:
    runs-on: [self-hosted, tests-runner]
    needs: [checkout]
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        target: [
            blueprint_hashes_plonk_sha256_process_test,
            blueprint_hashes_plonk_sha512_process_test,
            blueprint_non_native_plonk_non_native_demo_test,
            blueprint_non_native_plonk_non_native_range_test,
            blueprint_non_native_plonk_fixed_base_mul_test,
            blueprint_non_native_plonk_complete_addition_test,
            blueprint_non_native_plonk_var_base_mul_per_bit_test,
            blueprint_non_native_plonk_variable_base_multiplication_test,
          ]  # Tests to execute
    name: Run ${{ matrix.target }} on ${{ matrix.compiler }}
    steps:
      - name: Cleanup # TODO - move to scripts on runner
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true

      - name: Upload checkout job cache
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.CACHE_NAME }}-${{ matrix.compiler }}

      - name: Extract artifacts
        run: |
          archive_name=${{ env.CACHE_NAME }}-${{ matrix.compiler }}.tar.gz
          tar -xf $archive_name
          rm $archive_name

      - name: Build
        working-directory: ./build
        run: cmake --build . -t ${{ matrix.target }}

      - name: Run test
        working-directory: ./build
        run: |
          cd libs/${{ env.LIB_NAME }}/test
          COLOR='\033[0;33m'
          echo -e "${COLOR}${{ matrix.target }}"
          ./${{ matrix.target }}
